version: '3'
services:
  # Master Node
  spark-master:
    image: hackprotech/spark-multinode-cluster:latest
    container_name: 'spark-master'
    hostname: spark-master
    environment:
      - NODE_TYPE=MASTER
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
  # Worker Node 1 
  spark-worker-1:
    image: hackprotech/spark-multinode-cluster:latest
    container_name: 'worker-node-1'
    hostname: spark-worker1
    environment:
      - NODE_TYPE=WORKER
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
  # Worker Node 2 
  spark-worker-2:
    image: hackprotech/spark-multinode-cluster:latest
    container_name: 'worker-node-2'
    hostname: spark-worker2
    environment:
      - NODE_TYPE=WORKER
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  # Master Node
  master-node:
    image: hackprotech/multinode-apache-hadoop:latest
    container_name: 'master-node'
    hostname: master-node
    environment:
      - NODE_TYPE=MASTER
    ports:
      - '9000:9000'
      - '60075:50075'
      - '9870:9870'
      - '9866:9866'
      - '60020:50020'
      - '60070:50070'
      - '60470:50470'
      - '60475:50475'
      - '60010:50010'
      - '60090:50090'
  slave-node-1:
    image: hackprotech/multinode-apache-hadoop:latest
    container_name: 'slave-node-1'
    hostname:   slave-node-1
    environment:
      - NODE_TYPE=SLAVE1
    depends_on:
      - master-node
  slave-node-2:
    image: hackprotech/multinode-apache-hadoop:latest
    container_name: 'slave-node-2'
    hostname:   slave-node-2
    environment:
      - NODE_TYPE=SLAVE2
    depends_on:
      - master-node
networks:
  cluster-network:
    driver: bridge