version: '3'
services:

 # Master Node
  master-node:
    image: hackprotech/hadoop-and-spark-multinode-cluster:latest
    container_name: 'master-node'
    hostname: master-node
    environment:
      - NODE_TYPE=MASTER
    ports:
      # Hadoop Ports 
      - '9000:9000'
      - '60075:50075'
      - '9870:9870'
      - '9866:9866'
      - '60020:50020'
      - '60070:50070'
      - '60470:50470'
      - '60475:50475'
      - '60010:50010'
      - '60090:50090'
      # Spark Ports
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
  slave-node-1:
    image: hackprotech/hadoop-and-spark-multinode-cluster:latest
    container_name: 'slave-node-1'
    hostname:   slave-node-1
    environment:
      - NODE_TYPE=SLAVE  
      - SPARK_MASTER_URL=spark://master-node:7077
      - NODE_NUM=1
    depends_on:
      - master-node
  slave-node-2:
    image: hackprotech/hadoop-and-spark-multinode-cluster:latest
    container_name: 'slave-node-2'
    hostname:   slave-node-2
    environment:
      - NODE_TYPE=SLAVE
      - SPARK_MASTER_URL=spark://master-node:7077
      - NODE_NUM=2
    depends_on:
      - master-node
 
networks:
  cluster-network:
    driver: bridge