version: '3'
services:
  # Master Node
  master-node:
    image: hackprotech/apache-spark:3.0.0
    container_name: 'master-node'
    hostname: spark-master
    environment:
      - NODE_TYPE=MASTER
    ports:
      - '8081:8080'
      - '4040:4040'
      - '7077:7077'
  # Slave Node 1 
  slave-node-1:
    image: hackprotech/apache-spark:3.0.0
    container_name: 'slave-node-1'
    hostname: spark-worker1
    environment:
      - NODE_TYPE=SLAVE1
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - master-node
  # Slave Node 2 
  slave-node-2:
    image: hackprotech/apache-spark:3.0.0
    container_name: 'slave-node-2'
    hostname: spark-worker2
    environment:
      - NODE_TYPE=SLAVE2
      - SPARK_MASTER_URL=spark:/spark-master:7077
    depends_on:
      - master-node
networks:
  spark-network:
    driver: bridge