version: '3'
services:
  # Master Node
  spark-master:
    image: hackprotech/apache-spark:1.2.0
    container_name: 'master-node'
    hostname: spark-master
    ports:
      - '8080:8080'
  # Worker Node 1 
  spark-worker-1:
    image: hackprotech/apache-spark:1.2.0
    container_name: 'worker-node-1'
    hostname: spark-worker1
  # Worker Node 2 
  spark-worker-2:
    image: hackprotech/apache-spark:1.2.0
    container_name: 'worker-node-2'
    hostname: spark-worker2
networks:
  my-network:
    driver: bridge