version: '3'
services:
  spark-master:
    image: vengatesan/apache-spark
    container_name: 'master-node'
    ports:
      - '8080:8080'
  spark-worker-1:
    image: vengatesan/apache-spark
    container_name: 'worker-node-1'
  spark-worker-2:
    image: vengatesan/apache-spark
    container_name: 'worker-node-2'