version: '3'
services:
  # Master Node
  master-node:
    image: hackprotech/multinode-apache-hadoop:2.0.0
    container_name: 'master-node'
    hostname: master-node
    environment:
      - NODE_TYPE=MASTER
    ports:
      - '9000:9000'
      - '7001:50075'
      - '9870:9870'
      - '9866:9866'
      - '7002:50020'
      - '7003:50070'
      - '7004:50470'
      - '7005:50475'
      - '7006:50010'
      - '7007:50090'